// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy6yTpetcWjTDsNx6kGaqOLtDLC6rbj4s',
    appId: '1:428978225420:web:4ba3847edd0aa928f10929',
    messagingSenderId: '428978225420',
    projectId: 'chefease-d32f6',
    authDomain: 'chefease-d32f6.firebaseapp.com',
    storageBucket: 'chefease-d32f6.appspot.com',
    measurementId: 'G-HKJWTSLEQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcUJwjkm5nw6-qJSFVRU4QBIUe0A7S0GU',
    appId: '1:428978225420:android:daf7ce0f37cd1faaf10929',
    messagingSenderId: '428978225420',
    projectId: 'chefease-d32f6',
    storageBucket: 'chefease-d32f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn3iMBIMXANDYNGg-k0b2cC-vo0Lfddvo',
    appId: '1:428978225420:ios:6302260acb6d9d14f10929',
    messagingSenderId: '428978225420',
    projectId: 'chefease-d32f6',
    storageBucket: 'chefease-d32f6.appspot.com',
    androidClientId: '428978225420-meqtdml7f8lhvsdvm0tvtpq18f12nat1.apps.googleusercontent.com',
    iosClientId: '428978225420-h3af3no4kfdr0qrk7q4or68u2kvtefag.apps.googleusercontent.com',
    iosBundleId: 'com.chefease.chefease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy6yTpetcWjTDsNx6kGaqOLtDLC6rbj4s',
    appId: '1:428978225420:web:6d6d1874ae483d74f10929',
    messagingSenderId: '428978225420',
    projectId: 'chefease-d32f6',
    authDomain: 'chefease-d32f6.firebaseapp.com',
    storageBucket: 'chefease-d32f6.appspot.com',
    measurementId: 'G-68N2BTMTJ5',
  );

}